### Firstly, import all the required data sets.

In [1]:
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_70da622daeb44ea8afcfb1a97e5d1e45 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='XcvKkaMUsVhzVaga4jeE9pghFF8bLqodsmrNPXp7BzKC',
    ibm_auth_endpoint="https://iam.eu-gb.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')
body = client_70da622daeb44ea8afcfb1a97e5d1e45.get_object(Bucket='automatedpersonalityprediction-donotdelete-pr-3vfeqcye1yqchr',Key='train dataset.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )
# Train dataset
data = pd.read_csv(body)
data.head()
body = client_70da622daeb44ea8afcfb1a97e5d1e45.get_object(Bucket='automatedpersonalityprediction-donotdelete-pr-3vfeqcye1yqchr',Key='test dataset.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )
# TEST DATASET
testdata = pd.read_csv(body)
data.head()

Gender  Age  openness  neuroticism  conscientiousness  agreeableness  \
0    Male   17         7            4                  7              3   
1    Male   19         4            5                  4              6   
2  Female   18         7            6                  4              5   
3  Female   22         5            6                  7              4   
4  Female   19         7            4                  6              5   

   extraversion Personality (Class label)  
0             2               extraverted  
1             6                   serious  
2             5                dependable  
3             3               extraverted  
4             4                    lively

<h1 style="color:red"> Import all the required modules <h1>

In [2]:
import pandas as pd
from numpy import *
import numpy as np
from sklearn import preprocessing
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import neighbors

In [3]:
array = data.values

In [4]:
for i in range(len(array)):
	if array[i][0]=="Male":
		array[i][0]=1
	else:
		array[i][0]=0


In [5]:
df=pd.DataFrame(array)

In [6]:
maindf =df[[0,1,2,3,4,5,6]]

In [7]:
mainarray=maindf.values

In [8]:
print (mainarray)

[[1 17 7 ... 7 3 2]
 [1 19 4 ... 4 6 6]
 [0 18 7 ... 4 5 5]
 ...
 [1 22 5 ... 3 6 1]
 [1 19 5 ... 5 7 5]
 [0 18 5 ... 7 6 5]]


In [9]:
temp=df[7]
train_y =temp.values
print(train_y)

['extraverted' 'serious' 'dependable' 'extraverted' 'lively' 'lively'
 'extraverted' 'extraverted' 'dependable' 'lively' 'serious' 'extraverted'
 'lively' 'dependable' 'responsible' 'extraverted' 'serious' 'dependable'
 'responsible' 'extraverted' 'responsible' 'extraverted' 'responsible'
 'serious' 'serious' 'dependable' 'extraverted' 'extraverted' 'lively'
 'lively' 'extraverted' 'extraverted' 'dependable' 'lively' 'serious'
 'lively' 'responsible' 'responsible' 'dependable' 'serious' 'dependable'
 'extraverted' 'serious' 'extraverted' 'dependable' 'dependable'
 'responsible' 'serious' 'lively' 'lively' 'extraverted' 'extraverted'
 'serious' 'extraverted' 'lively' 'lively' 'extraverted' 'dependable'
 'lively' 'lively' 'responsible' 'extraverted' 'responsible' 'dependable'
 'serious' 'serious' 'responsible' 'dependable' 'responsible' 'dependable'
 'extraverted' 'extraverted' 'responsible' 'dependable' 'responsible'
 'serious' 'extraverted' 'dependable' 'lively' 'lively' 'extraverted'


In [10]:
print(mainarray)

[[1 17 7 ... 7 3 2]
 [1 19 4 ... 4 6 6]
 [0 18 7 ... 4 5 5]
 ...
 [1 22 5 ... 3 6 1]
 [1 19 5 ... 5 7 5]
 [0 18 5 ... 7 6 5]]


In [11]:
train_y=temp.values

In [12]:
for i in range(len(train_y)):
	train_y[i] =str(train_y[i])

In [13]:
mul_lr = linear_model.LogisticRegression(multi_class='multinomial', solver='newton-cg',max_iter =1000)

In [14]:
mul_lr.fit(mainarray, train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=1000, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=None, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False)

<h2 style="color:red"> Now that you've trained your data using Logistic Regression
It is time for you to test the dataset. </h2>

In [52]:
testdata.head()

Gender  Age  openness  neuroticism  conscientiousness  agreeableness  \
0  Female   20         7            9                  9              5   
1    Male   17         5            4                  5              2   
2  Female   25         5            5                  7              2   
3  Female   18         6            2                  7              4   
4  Female   19         2            4                  7              1   

   extraversion Personality (class label)  
0             5                dependable  
1             4                   serious  
2             4                   serious  
3             7                   serious  
4             3               responsible

In [53]:
test = testdata.values

In [54]:
for i in range(len(test)):
	if test[i][0]=="Male":
		test[i][0]=1
	else:
		test[i][0]=0


In [55]:
df1=pd.DataFrame(test)

In [56]:
testdf =df1[[0,1,2,3,4,5,6]]

In [57]:
maintestarray=testdf.values

In [58]:
print(maintestarray)

[[0 20 7 ... 9 5 5]
 [1 17 5 ... 5 2 4]
 [0 25 5 ... 7 2 4]
 ...
 [1 18 7 ... 6 2 7]
 [1 23 6 ... 5 4 3]
 [0 18 5 ... 3 5 6]]


<h1 style="color:red; font-size:24px"> Now that the testing of the data is done. <br> Let's focus on predicting the output</h1>

In [59]:
y_pred = mul_lr.predict(maintestarray)

<h2 style="color:blue"> Predict all the values using a for loop </h2>

In [60]:
for i in range(len(y_pred)) :
	y_pred[i]=str((y_pred[i]))

<h2 style="color:blue"> Name the output table </h2>

In [61]:
DF = pd.DataFrame(y_pred,columns=['Predicted Personality'])

In [62]:
# Start from index 1
DF.index=DF.index+1

<h2 style="color:blue"> Name the index column </h2>

In [68]:
DF.index.names = ['Person Index Number']

<h2 style="color:blue;font-size:22px"> Display the predicted output </h2>

In [69]:
DF

Predicted Personality
Person Index Number                      
1                              dependable
2                                 serious
3                                 serious
4                                 serious
5                             responsible
6                                 serious
7                                 serious
8                                 serious
9                                 serious
10                                serious
11                                serious
12                            responsible
13                            responsible
14                                serious
15                                 lively
16                            extraverted
17                                serious
18                                serious
19                                serious
20                            extraverted
21                                serious
22                            extraverted
23                                serious
24                            extraverted
25                                serious
26                                serious
27                            extraverted
28                            extraverted
29                                serious
30                            responsible
...                                   ...
286                            dependable
287                               serious
288                           extraverted
289                           extraverted
290                           extraverted
291                           extraverted
292                           extraverted
293                           extraverted
294                               serious
295                           extraverted
296                           extraverted
297                           extraverted
298                           extraverted
299                           extraverted
300                           extraverted
301                               serious
302                               serious
303                               serious
304                               serious
305                               serious
306                               serious
307                               serious
308                               serious
309                               serious
310                               serious
311                           extraverted
312                               serious
313                               serious
314                           extraverted
315                           extraverted

[315 rows x 1 columns]